# Site settings
title: Sazed
description: Sazed's description
url: "http://yourdomain.com" # the base hostname & protocol for your site
copyright: Copyright &copy; Abhay Rana
email: me@captnemo.in
repo: captn3m0/sazed
categories:
  top: Main Articles
  policy: Policy
# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed